# Generated by Django 5.0.14 on 2026-04-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_asistencia_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_requeridos', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_recompensa',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]