# Generated by Django 5.0.14 on 2026-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]