# Generated by Django 5.0.14 on 2026-04-22 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_recompensa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id_canje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.usuario')),
            ],
            options={
                'db_table': 'core_canje_recompensa',
                'ordering': ['-fecha_canje'],
                'managed': True,
            },
        ),
    ]