# Generated by Django 5.0.14 on 2026-04-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_canje_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='recompensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recompensa'),
        ),
    ]