# Generated by Django 5.0.14 on 2026-04-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_puntaje_recompensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(blank=True, max_length=20)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_contact_message',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='puntos_asignados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
