# Generated by Django 4.2 on 2026-05-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
