# Generated by Django 4.2 on 2026-05-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='recompensa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='CanjeRecompensa',
        ),
        migrations.DeleteModel(
            name='Recompensa',
        ),
    ]
