# Generated by Django 4.2 on 2026-05-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_inscripcion_options_remove_puntaje_recompensa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_requeridos', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/')),
                ('disponible', models.BooleanField(default=True)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_recompensa',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='id',
            new_name='id_inscripcion',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='jornada',
            field=models.ForeignKey(db_column='jornada_id', on_delete=django.db.models.deletion.CASCADE, to='core.jornada'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id_canje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.usuario')),
            ],
            options={
                'db_table': 'core_canje_recompensa',
                'ordering': ['-fecha_canje'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='puntaje',
            name='recompensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recompensa'),
        ),
    ]
