# Generated by Django 4.2 on 2026-06-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recompensa_rename_id_inscripcion_id_inscripcion_and_more'),
    ]

    operations = [
    ]
