# Generated by Django 4.2 on 2026-06-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaSemanal',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_educativo', models.TextField()),
                ('preguntas_json', models.JSONField()),
                ('vista_destino', models.CharField(choices=[('residente', 'Residente'), ('organizador', 'Organizador')], default='residente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(limit_choices_to={'rol': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'db_table': 'core_tema_semanal',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('total_preguntas', models.IntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.temasemanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'core_resultado_evaluacion',
                'managed': True,
                'unique_together': {('usuario', 'tema')},
            },
        ),
    ]
