# Generated by Django 4.2 on 2026-06-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_temasemanal_resultadoevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
