from django.urls import path
from . import views

urlpatterns = [
    path("panel/admin/", views.admin_panel, name="admin_panel"),

    path("admi/asistencia/", views.admi_asistencia, name="admi_asistencia"),
    path('admi/acciones/validar/', views.admi_validar_acciones, name='admi_validar_acciones'),
    path('admi/asistencia/validar/', views.admi_validar_asistencia, name='admi_validar_asistencia'),
    path("admi/creacionjornadas/", views.admi_creacion_jornadas, name="admi_creacion_jornadas"),
    path("admi/foro/", views.admi_publicacion_foro, name="admi_publicacion_foro"),
    path("admi/foro/publicaciones/", views.admi_foro_publicaciones, name="admi_foro_publicaciones"),
    path('admi/foro/publicacion/editar/<int:publicacion_id>/', views.admi_editar_publicacion, name='admi_editar_publicacion'),
    path('admi/foro/publicacion/eliminar/<int:publicacion_id>/', views.admi_eliminar_publicacion, name='admi_eliminar_publicacion'),
    path("admi/recoleccion/", views.admi_recoleccion, name="admi_recoleccion"),
    path("admi/recompensa/", views.admi_recompensa, name="admi_recompensa"),
    path("admi/recompensa/<int:recompensa_id>/canjes/", views.admi_recompensa_canjes, name="admi_recompensa_canjes"),
    path("admi/historial-canjes/", views.admi_historial_canjes, name="admi_historial_canjes"),
    path("admi/inicio/", views.admi_inicio, name="admi_inicio"),
    path("admi/educacion/", views.admi_educacion, name="admi_educacion"),
    path("admi/contacto/", views.admi_contacto, name="admi_contacto"),
    path('admi/usuarios/', views.panel_usuarios, name="panel_usuarios"),
    path("admi/usuarios/agregar/", views.agregar_usuario, name="agregar_usuario"),
    path("admi/usuarios/editar/<int:id>/", views.editar_usuario, name="editar_usuario"),
    path("admi/usuarios/suspender/<int:id>/", views.suspender_usuario, name="suspender_usuario"),
    path('admin/usuarios/', views.admin_users_list, name='admin_users_list'),
    path('admin/usuarios/<int:id_usuario>/suspend/', views.admin_users_suspend, name='admin_users_suspend'),
    path('admin/usuarios/<int:id_usuario>/suspend/confirm/', views.admin_users_suspend_confirm, name='admin_users_suspend_confirm'),
    path('admin/usuarios/<int:id_usuario>/restore/', views.admin_users_restore, name='admin_users_restore'),
    path('admin/usuarios/deleted/', views.admin_users_deleted, name='admin_users_deleted'),
    path('admin/usuarios/export/xlsx/', views.admin_users_export_xlsx, name='admin_users_export_xlsx'),
    path('admin/usuarios/export/pdf/', views.admin_users_export_pdf, name='admin_users_export_pdf'),
    path('admin/usuarios/api/search/', views.admin_users_api_search, name='admin_users_api_search'),
    path('admi/usuarios/eliminar/<int:id_usuario>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('admi/usuarios/reactivar/<int:id>/', views.reactivar_usuario, name='reactivar_usuario'),
    path('administrador/puntaje/asignar/', views.asignar_puntaje, name='asignar_puntaje'),
    path('administrador/puntaje/asignar/', views.asignar_puntaje, name='asignar_puntaje_admin'),
    path('admi/perfil/', views.perfil_admin, name='perfil_admin'),
    path('admi/perfil/cambiar-foto/', views.cambiar_foto_admin, name='cambiar_foto_admin'),
    path('admi/notificaciones/', views.admi_notificaciones, name='admi_notificaciones'),
    path('admi/notificaciones/', views.admi_notificaciones, name='notificaciones'),
    path('admi/jornadas/modificar/<int:jornada_id>/', views.admi_modificar_jornada, name='admi_modificar_jornada'),
    path('admi/jornadas/eliminar/<int:jornada_id>/', views.admi_eliminar_jornada, name='admi_eliminar_jornada'),
    path('admi/jornadas/detalle/<int:jornada_id>/', views.admi_detalle_jornada, name='admi_detalle_jornada'),
    path('admi/jornadas/detalle/<int:jornada_id>/', views.admi_detalle_jornada, name='detalle_jornada'),
    path('admi/configuracion/', views.admi_configuracion, name='admi_configuracion'),
    path('historial/puntaje/<int:id_usuario>/', views.historial_puntaje, name='historial_puntaje'),
    path('historial/puntaje/<int:id_usuario>/', views.historial_puntaje, name='historial_puntaje_admin'),
    path('tema-semanal/', views.admin_generar_tema, name='admin_tema_semanal'),
    path('api/educacion/', views.educacion_api, name='educacion_api'),
    path('api/evaluacion/guardar/', views.guardar_evaluacion, name='guardar_evaluacion'),
]